name: Deploy REST API

on:
  push:
    branches: [production-web]

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh commands
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        username: ${{ secrets.SSH_USERNAME }}
 
        script: |
          cd ~/Tomato-Disease-Classification
          git checkout production-web
          git fetch origin
          git reset --hard origin/production-web
          docker build -t tomato-disease-classifier .
          docker restart $(docker ps -q)